logging:
  level:
    root: INFO
    com.example.keycloak: DEBUG

keycloak:
  api:
    url: http://localhost:8180/auth/
    client-id: manage-users-client
    client-secret: c87e8852-3119-4c93-a0f7-082520e1daa2
    grant-type: client_credentials
#    client-id: dev-direct-grant-cli
#    client-secret: 9ee6f35d-c4e5-4c1f-ba48-2b6b4b00e7d1
#    grant-type: client_credentials
    realm: app
