logging:
  level:
    root: INFO
    com.example.keycloak: DEBUG

keycloak:
  api:
    # Expected to have configured a client
    # - in app realm
    # - with Client ID manage-users-client
    # - client authentication enabled and client-secret updated with the generated secret
    # - Service accounts role enabled, and assigned 'manage-users'
    server-url: http://localhost:8180
    realm: app
    client-id: manage-users-client
    client-secret: WaMJOGUZxiWdEXCpMJj5tqP97kDP5Dyg
    grant-type: client_credentials
#    client-id: dev-direct-grant-cli
#    client-secret: 9ee6f35d-c4e5-4c1f-ba48-2b6b4b00e7d1
#    grant-type: client_credentials
