logging:
  level:
    root: INFO
    com.example.keycloak: DEBUG

keycloak:
  api:
    server-url: http://localhost:8180/auth/
    realm: app
    client-id: manage-users-client
    client-secret: f8feac94-fcb6-43ab-bbad-07727f7c9c34
    grant-type: client_credentials
#    client-id: dev-direct-grant-cli
#    client-secret: 9ee6f35d-c4e5-4c1f-ba48-2b6b4b00e7d1
#    grant-type: client_credentials
