services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: keycloak
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - source: ./providers/target/providers-jar-with-dependencies.jar
        target: /opt/jboss/keycloak/standalone/deployments/providers-jar-with-dependencies.jar
        type: bind

